version: '3.7'

services:
  db:
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=metabasedb
      - MYSQL_USER=pi
      - MYSQL_PASSWORD=raspberry
    restart: always

  metabase:
    build: ./metabase
    container_name: metabase
    ports:
      - 3000:3000
    volumes:
      - /dev/urandom:/dev/random:ro
      - ./metabase/data:/metabase-data
      - ./metabase/plugins:/plugins
    environment:
      - MB_DB_TYPE=mysql
      - MB_DB_HOST=db
      - MB_DB_DBNAME=metabasedb
      - MB_DB_USER=pi
      - MB_DB_PASS=raspberry
    restart: always
    depends_on: 
      - db
